name = "TestExtensionNameClash"
uuid = "8eb442a4-9dd2-4fc6-8f24-df26076fe5a9"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.0"

[deps]
PlotlyExtensionsHelper = "a7e57fc7-3548-4021-90c3-ac0e175068b1"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = ["PlotlyBase"]